### ISSUE TITLE
There should be a way to make a feature request more easily

### ISSUE THREAD

**Issue by kleberbaum** [erebos-xyz/test#1]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it takes a lot of time to make a  feature request.

**Describe the solution you'd like**
It would be a bliss to have a trimmed down feature request.

**Additional context**
Ref: https://github.com/erebos-xyz/test/blob/master/.github/ISSUE_TEMPLATE/quick_request.md

**Comment by petschna** [comment]
This issue has been resolved with a PR. #4
