### ISSUE TITLE
There should be a goldfish

### ISSUE THREAD

**Issue by petute** [erebos-xyz/test#3]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there isn't a goldfish in this far to big aquarium.

**Describe the solution you'd like**
Buy a goldfish.

**Additional context**
Ref: https://aquariumtidings.com/wp-content/uploads/2014/06/Depositphotos_5125679_original.jpg

**Comment by kleberbaum** [comment]
This issue has been resolved with a PR. #6
